"""Twenty original teaching tasks. All solutions use the supported subset."""


def task(key, title, topic, level, args, prompt, solution, examples, hints):
    signature = f"def solve({args}):"
    return {"id": key, "title": title, "topic": topic, "level": level,
            "function": "solve", "prompt": prompt, "starter": signature + "\n    pass\n",
            "solution": signature + "\n" + solution + "\n", "hints": hints,
            "tests": [{"args": a, "expected": b, "note": n} for a, b, n in examples]}


TASKS = [
 task("C1", "Positive, negative or zero", "Conditions", 1, "n",
      'Return "positive", "negative" or "zero" for integer n.',
      '    if n > 0:\n        return "positive"\n    if n < 0:\n        return "negative"\n    return "zero"',
      [([3], "positive", "Positive"), ([-4], "negative", "Negative"), ([0], "zero", "Zero boundary"), ([1], "positive", "Small positive")],
      ["There are three cases.", "Use > 0 and < 0 checks.", "If neither check is true, the number is zero."]),
 task("C2", "Even number", "Conditions", 1, "n", "Return True if integer n is even; otherwise False.",
      "    return n % 2 == 0", [([4], True, "Even"), ([3], False, "Odd"), ([0], True, "Zero"), ([-2], True, "Negative even")],
      ["Think about the remainder.", "Use n % 2.", "Even numbers have a remainder of zero."]),
 task("C3", "Largest of three", "Conditions", 2, "a, b, c", "Return the largest of three integers, including ties.",
      "    best = a\n    if b > best:\n        best = b\n    if c > best:\n        best = c\n    return best",
      [([1, 4, 2], 4, "Middle largest"), ([9, 3, 1], 9, "First largest"), ([-8, -3, -5], -3, "All negative"), ([2, 2, 2], 2, "Tie"), ([1, 2, 7], 7, "Last largest")],
      ["Keep the best value seen so far.", "Start with a, not zero.", "Compare both b and c with best."]),
 task("C4", "Leap year", "Conditions", 2, "year", "Return True for a Gregorian leap year. Divisible by 400, or divisible by 4 but not 100.",
      "    return year % 400 == 0 or (year % 4 == 0 and year % 100 != 0)",
      [([2024], True, "Multiple of four"), ([2023], False, "Ordinary year"), ([1900], False, "Century exception"), ([2000], True, "Four-century exception")],
      ["Century years need a separate check.", "A multiple of 400 is always a leap year.", "Otherwise require divisible by 4 AND not by 100."]),
 task("C5", "Valid triangle", "Conditions", 3, "a, b, c", "Return True only if positive side lengths form a triangle. Each pair sum must exceed the third side.",
      "    return a > 0 and b > 0 and c > 0 and a+b > c and a+c > b and b+c > a",
      [([3, 4, 5], True, "Triangle"), ([1, 2, 3], False, "Equality is invalid"), ([0, 2, 2], False, "Zero"), ([-1, 2, 2], False, "Negative"), ([8, 2, 3], False, "First too long")],
      ["Check positivity and all three sums.", "Equality is not enough.", "Join the required checks with and."]),
 task("L1", "Sum from 1 to n", "Loops", 1, "n", "Return 1 + 2 + ... + n for integer n >= 0. For n=0 return 0.",
      "    total = 0\n    for i in range(1, n+1):\n        total += i\n    return total",
      [([3], 6, "Small sum"), ([1], 1, "One"), ([0], 0, "Zero"), ([10], 55, "Larger sum")],
      ["Use an accumulator starting at zero.", "range stops before its end value.", "Use range(1, n+1), adding i each time."]),
 task("L2", "Count even values", "Loops", 1, "nums", "Return how many integers in nums are even. An empty list returns 0.",
      "    count = 0\n    for n in nums:\n        if n % 2 == 0:\n            count += 1\n    return count",
      [([[1, 2, 4]], 2, "Mixed"), ([[]], 0, "Empty"), ([[0, -2, 3]], 2, "Zero and negative"), ([[1, 3]], 0, "No evens")],
      ["Check each item once.", "Increase the count only for an even item.", "count += 1 belongs inside the if block."]),
 task("L3", "Factorial", "Loops", 2, "n", "Return n! for 0 <= n <= 12. Remember 0! = 1.",
      "    result = 1\n    for i in range(1, n+1):\n        result *= i\n    return result",
      [([4], 24, "Four"), ([0], 1, "Zero factorial"), ([1], 1, "One"), ([6], 720, "Six")],
      ["Factorial is repeated multiplication.", "Start at one, not zero.", "Multiply by every integer from 1 through n."]),
 task("L4", "Sum digits", "Loops", 2, "n", "Return the sum of decimal digits of an integer. Ignore a negative sign.",
      "    n = abs(n)\n    total = 0\n    while n > 0:\n        total += n % 10\n        n = n // 10\n    return total",
      [([123], 6, "Ordinary"), ([0], 0, "Zero"), ([-42], 6, "Negative"), ([1009], 10, "Internal zeros")],
      ["Take the absolute value first.", "% 10 extracts the last digit.", "Use // 10 to remove each processed digit."]),
 task("L5", "Prime check", "Loops", 3, "n", "Return True if integer n is prime. Values below 2 are not prime. Inputs are at most 200.",
      "    if n < 2:\n        return False\n    for i in range(2, n):\n        if n % i == 0:\n            return False\n    return True",
      [([7], True, "Prime"), ([9], False, "Composite"), ([2], True, "Smallest prime"), ([1], False, "One"), ([-3], False, "Negative")],
      ["Handle numbers below two first.", "Look for a divisor from 2 to n-1.", "Return True only after finishing all divisor checks."]),
 task("F1", "Square a number", "Functions", 1, "n", "Return the square of integer n. Use return, not print.",
      "    return n * n", [([3], 9, "Positive"), ([-4], 16, "Negative"), ([0], 0, "Zero"), ([1], 1, "One")],
      ["A square multiplies the number by itself.", "The task expects a returned value.", "Write return n * n."]),
 task("F2", "Absolute difference", "Functions", 1, "a, b", "Return the non-negative difference between two numbers.",
      "    return abs(a-b)", [([8, 3], 5, "First larger"), ([3, 8], 5, "Second larger"), ([4, 4], 0, "Equal"), ([-2, 3], 5, "Mixed signs")],
      ["The result cannot be negative.", "Subtract a and b, then remove the sign.", "Use abs(a-b)."]),
 task("F3", "Clamp a value", "Functions", 2, "n, low, high", "Return n limited to the inclusive interval [low, high]. Assume low <= high.",
      "    if n < low:\n        return low\n    if n > high:\n        return high\n    return n",
      [([5, 1, 9], 5, "Inside"), ([-2, 1, 9], 1, "Below"), ([20, 1, 9], 9, "Above"), ([1, 1, 1], 1, "Single point")],
      ["There are below, inside and above cases.", "Outside values return a boundary.", "Inside values must return n unchanged."]),
 task("F4", "Greatest common divisor", "Functions", 2, "a, b", "Return the non-negative GCD of two integers. For (0,0), return 0.",
      "    a = abs(a)\n    b = abs(b)\n    while b != 0:\n        a, b = b, a % b\n    return a",
      [([12, 8], 4, "Shared divisor"), ([7, 3], 1, "Coprime"), ([0, 5], 5, "One zero"), ([0, 0], 0, "Both zero"), ([-6, 9], 3, "Negative")],
      ["Use Euclid's remainder rule.", "Repeat (a,b) = (b,a%b) until b is zero.", "Normalize signs using abs first."]),
 task("F5", "Palindrome", "Functions", 3, "text", "Return True if text reads the same forwards and backwards. Case and spaces matter; empty text returns True.",
      "    return text == text[::-1]",
      [(["level"], True, "Palindrome"), (["hello"], False, "Not palindrome"), ([""], True, "Empty"), (["Aa"], False, "Case matters"), (["a"], True, "One character")],
      ["Compare text with its reverse.", "[::-1] reverses a sequence.", "Return text == text[::-1]."]),
 task("A1", "List total", "Lists", 1, "nums", "Return the total of all integers in nums. An empty list returns 0.",
      "    total = 0\n    for n in nums:\n        total += n\n    return total",
      [([[2, 3, 4]], 9, "Positive"), ([[]], 0, "Empty"), ([[-2, 2]], 0, "Mixed signs"), ([[5]], 5, "Single item")],
      ["Start with total = 0.", "Add each list value to total.", "Return after the loop, not inside it."]),
 task("A2", "Largest list value", "Lists", 1, "nums", "Return the largest integer in nums. Return None for an empty list.",
      "    if len(nums) == 0:\n        return None\n    best = nums[0]\n    for n in nums:\n        if n > best:\n            best = n\n    return best",
      [([[1, 9, 2]], 9, "Mixed"), ([[-8, -2, -5]], -2, "All negative"), ([[]], None, "Empty"), ([[3]], 3, "One item"), ([[2, 2]], 2, "Duplicate")],
      ["Consider an empty list first.", "For a non-empty list, start with nums[0], not zero.", "Update best whenever a larger item appears."]),
 task("A3", "Unique values in order", "Lists", 2, "nums", "Return a new list with duplicates removed, preserving first occurrence order. Use result = result + [n]; methods are outside this runner's subset.",
      "    result = []\n    for n in nums:\n        if n not in result:\n            result = result + [n]\n    return result",
      [([[3, 1, 3, 2]], [3, 1, 2], "Order"), ([[]], [], "Empty"), ([[2, 2, 2]], [2], "All same"), ([[-1, 0, -1]], [-1, 0], "Negative")],
      ["Build a new list.", "Use n not in result before adding.", "Use result = result + [n] to add a new value."]),
 task("A4", "Second distinct largest", "Lists", 2, "nums", "Return the second largest distinct value. Return None if fewer than two distinct values exist.",
      "    values = []\n    for n in nums:\n        if n not in values:\n            values = values + [n]\n    if len(values) < 2:\n        return None\n    values = sorted(values)\n    return values[-2]",
      [([[3, 8, 8, 5]], 5, "Duplicates"), ([[1]], None, "One"), ([[]], None, "Empty"), ([[-4, -1, -2]], -2, "Negative"), ([[2, 2]], None, "One distinct")],
      ["Remove duplicate values first.", "Check that at least two distinct values exist.", "Sort and return the item at index -2."]),
 task("A5", "Rotate right", "Lists", 3, "nums, k", "Return nums rotated right by k positions, with integer k >= 0. Return [] for an empty list.",
      "    if len(nums) == 0:\n        return []\n    k = k % len(nums)\n    return nums[-k:] + nums[:-k]",
      [([[1, 2, 3], 1], [3, 1, 2], "One step"), ([[1, 2, 3], 0], [1, 2, 3], "Zero steps"), ([[], 5], [], "Empty"), ([[1, 2, 3], 4], [3, 1, 2], "Wraparound"), ([[9], 2], [9], "Single item")],
      ["An empty list needs a guard.", "Use k % len(nums) to reduce large k.", "Join the last k values and the remaining prefix."]),
]
TASK_BY_ID = {t["id"]: t for t in TASKS}
TOPICS = ["Conditions", "Loops", "Functions", "Lists"]
